### ISSUE TITLE
excluded-source-pathname-p errors on a pthname when empty-string name

### ISSUE THREAD

**Issue by Yehouda** [privet-kitty/wild-package-inferred-system#2]
excluded-source-pathname-p signals an error if given a pathname wher ethe name field is an empty string rather than NIL. 

The test calls it by hand on "foo/bar/.lisp", which on LispWorks gives you the name as empty string,

**Comment by privet-kitty** [comment]
Thank you! At a glance, just adding the case `(zerop (length name))` seems to be enough, though I will check it later.

**Comment by Yehouda** [comment]
Should really check that the length is bigger than 1, so don't fail on one character string.

**Comment by privet-kitty** [comment]
Probably I don't get your point. To be specific, which pathname produces a problem with change like

```lisp
(defun excluded-source-pathname-p (pathname)
  "WILD-PACKAGE-INFERRED-SYSTEM ignores the file names beginning with dot `.'
and file types .nosystem.lisp and .script.lisp even if they match a given
wild-pathname."
  (let ((name (pathname-name pathname)))
    (or (not (stringp name))
        (zerop (length name))
        (char= #\. (char name 0))
        (let ((second-type (nth-value 1 (split-name-type name))))
          (or (equal second-type "script")
              (equal second-type "nosystem"))))))
```

**Comment by Yehouda** [comment]
Sorry, that was a "typo". It was intended to b an answer to an issue in another project. 
Sorry for the noise.
